# =========================================================
# RENDER BLUEPRINT FOR RESUMEIQ SPRING BOOT BACKEND
# =========================================================

services:
  - type: web
    name: resumeiq-backend
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: GOOGLE_API_KEYS
        sync: false
