spring.application.name=resumeiq-backend

# MySQL Datasource Configuration (Configurable via DB_URL, DB_USERNAME, DB_PASSWORD environment variables or properties below)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ResumeIQ?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:chaitu}
spring.datasource.password=${DB_PASSWORD:A11@CHAITU143}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}
